### Faz embedding da entrada e procura
GET http://localhost:3000/search-formula?formula="""$\begin{align*} R&=Sym(V^*(-2)), & R^{\vee}&=Sym(V\langle 2\rangle). \\ \Lambda&=Sym(V^*(-2)[1]), & \Lambda^{\vee}&=Sym(V^*\langle-2\rangle[1]). \end{align*}$"""&mode=DIRECT


### Tokeniza a entrada, faz embedding da entrada e procura 
GET http://localhost:3000/search-formula?formula="""$\begin{align*} R&=Sym(V^*(-2)), & R^{\vee}&=Sym(V\langle 2\rangle). \\ \Lambda&=Sym(V^*(-2)[1]), & \Lambda^{\vee}&=Sym(V^*\langle-2\rangle[1]). \end{align*}$"""&mode=TOKENIZED


### REQ 2
POST http://192.168.56.1:8080/api/formulas/process
Content-Type: application/json

{
  "formula": "(\\int_{-\\infty}^{\\infty} e^{-x^2}dx=\\sqrt{\\pi})"
}

###
POST http://localhost:8000/embed
Content-Type: application/json

{
  "text": "x+y"
}